LV1終了
ajk0421/hello_world_rails pull request #7
Opened 2019-04-10 15:38 UTC by ajk0421

2019-04-10 16:08 UTC, mc-chinju requested changes
直すとこありまーす

2019-04-10 16:08 UTC, mc-chinju commented on config/application.rb
> +>>>>>>> 3d21338... Lv1.終了
コンフリクト解消の残骸があるので、ここは直しておきましょう！

2019-04-10 16:08 UTC, mc-chinju commented on app/controllers/users_controller.rb
> +    binding.pry
👀

2019-04-10 16:08 UTC, mc-chinju commented on Gemfile.lock
> +>>>>>>> 3d21338... Lv1.終了
ここもコンフリクト解消の残骸があるので、直しておきましょう！

2019-04-11 03:53 UTC, ajk0421 commented
お疲れ様です！
指摘された3箇所、修正しました！
よろしくお願いいたします！

2019-04-11 05:00 UTC, ajk0421 commented
他のブランチをマージした際のコンフリクトも解消しました！

2019-04-11 05:34 UTC, mc-chinju approved these changes
いいすね！LGTM！

2019-04-11 05:37 UTC, merged